baseURL = "https://dogger-app.netlify.app"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Dogger"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "ул. Петербургская, 52, Казань, Респ. Татарстан, 420074"
author = "Основатели проекта"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "Приложение для владельцев собак"
email = "itco.dogger@gmail.com"
google_analytics_id = ""
home = "Home"
logo = ""
phone = "+7 999 169 26 84"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "https://formspree.io/itco.dogger@gmail.com"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "55.7805015"
map_longitude = "49.1335273"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/timyr.badretdinov"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/svoy.tim.baton/"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "https://twitter.com/britny1999"
icon = "ti-twitter-alt"
